---
- name: Clone keyd repository
  ansible.builtin.git:
    repo: https://github.com/rvaiya/keyd
    dest: /tmp/keyd
    update: false

- name: Build and install keyd
  ansible.builtin.shell:
    cmd: make -j$(nproc) && make install
    chdir: /tmp/keyd
  changed_when: false

- name: Enable and start keyd service
  ansible.builtin.systemd:
    name: keyd
    enabled: true
    state: started
