---
- name: Clone ly repository
  ansible.builtin.git:
    repo: https://codeberg.org/fairyglade/ly.git
    dest: /tmp/ly
    update: false

- name: Build ly using zig
  ansible.builtin.command:
    cmd: "{{ workstation_home }}/architecture/toolchains/zig/zig build"
    chdir: /tmp/ly
  changed_when: false

- name: Install ly with systemd init
  ansible.builtin.command:
    cmd: "{{ workstation_home }}/architecture/toolchains/zig/zig build installexe -Dinit_system=systemd"
    chdir: /tmp/ly
  changed_when: false
