---
- name: Install Android tools
  ansible.builtin.apt:
    name:
      - adb
      - fastboot
      - heimdall-flash
    state: present
    update_cache: true
    install_recommends: false
  tags:
    - pkg
    - pkg_android
