---
- name: Install build tools and development helpers
  ansible.builtin.apt:
    name:
      - automake
      - autotools-dev
      - cmake
      - make
      - meson
      - ninja-build
    state: present
    update_cache: true
    install_recommends: true
