---
- name: Detect GCC version
  ansible.builtin.command:
    cmd: gcc -dumpversion
  register: gcc_version
  changed_when: false

- name: Extract GCC major version
  ansible.builtin.set_fact:
    gcc_major_version: "{{ gcc_version.stdout.split('.')[0] }}"

- name: Install development libraries
  ansible.builtin.apt:
    name:
      - "libgcc-{{ gcc_major_version }}-dev"
      - "libgccjit-{{ gcc_major_version }}-dev"
      - gobject-introspection
      - lbzip2
      - libacl1-dev
      - libasound2-dev
      - libassuan-dev
      - libc6-dev
      - libcatch2-dev
      - libdatrie-dev
      - libdbus-1-dev
      - libdbusmenu-gtk3-dev
      - libevdev-dev
      - libfmt-dev
      - libgif-dev
      - libgirepository1.0-dev
      - libgnutls28-dev
      - libgpg-error-dev
      - libgpm-dev
      - libgtk-3-dev
      - libgtk2.0-dev
      - libgtkmm-3.0-dev
      - libice-dev
      - libinput-dev
      - libjansson-dev
      - libjpeg-dev
      - libjsoncpp-dev
      - liblockfile-dev
      - liblqr-1-0
      - libm17n-dev
      - libmagick++-dev
      - libmagickwand-dev
      - libmagickwand-dev
      - libmpdclient-dev
      - libncurses-dev
      - libncurses5-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnotify-dev
      - libotf-dev
      - libpam0g-dev
      - libpng-dev
      - libpulse-dev
      - librsvg2-dev
      - libselinux1-dev
      - libsigc++-2.0-dev
      - libsm-dev
      - libspdlog-dev
      - libsqlite3-dev
      - libthai-dev
      - libtiff-dev
      - libtiff5-dev
      - libtinfo-dev
      - libtool
      - libtree-sitter-dev
      - libwayland-dev
      - libx11-dev
      - libxaw7-dev
      - libxcb-xkb-dev
      - libxext-dev
      - libxi-dev
      - libxkbregistry-dev
      - libxml2-dev
      - libxmu-dev
      - libxmuu-dev
      - libxpm-dev
      - libxrandr-dev
      - libxt-dev
      - libxtst-dev
      - libxv-dev
      - quilt
      - sharutils
      - xaw3dg
      - xaw3dg-dev
      - xorg-dev
      - xutils-dev
      - zlib1g-dev
    state: present
    update_cache: true
    install_recommends: false
  ignore_errors: true
  register: ignore_errors_register
  tags:
    - pkg
    - pkg_libs
