ansible_become_password: ENC[AES256_GCM,data:yDrXUnOi63/bfsw=,iv:JXaAOcZZZjHtEC5agbnNxvC+0oXV7qM3Ur/hB58nBAE=,tag:/tRj1iTaDi0MR156NPkX1g==,type:str]
sops:
    lastmodified: "2026-06-19T17:37:26Z"
    mac: ENC[AES256_GCM,data:QbwbJOiBZCsFyI2ypNWhagRbOXmoXCqUDyUIu0agM1scE+d3hOmv8ANs2oZnjRfmW+uhM2ulm2jeAiw8iQcZMqu6URoesUIxV74OorR1De8o22dl69ad0EE10+VWjHrQqIX4vYaC+xQgv7UVoOOUyWeO5yYj5cCXX2Vlwa4QG1I=,iv:bFRKEzIB5c6QAO5voY1Z7l3aYgAMV84KD1vPrdOslXg=,tag:pdHUex02yvL3eupHdf30JA==,type:str]
    pgp:
        - created_at: "2026-06-19T17:37:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//RgMvgmaotJiytdcQ5zQUmj+7aojhuPOJQ1dyA9TZz6Tu
            Y8XuduBYpQ0zzN/BbeH7a3wTyOQyHjISr7dmcoVMpntXDYRF8YpWN5tuK6n2KyAZ
            wL5eh8Gu9uRUY5rK6ytrd90mxz0Fn33FuP3+TJUOsVAHDTvm3q7tdk5bSARYwFZt
            lT7quYxT6gktiFXUC2BOlbGZrmq5nGeJc424nPDlher97BE8KVlSdW0wE0YWEOx3
            wWF0/sgj/jb182eoTUldtY5x2CRPCJn8ozi/EI+Cz9OUawJm7MTwCMG1inc5VVhQ
            sXoycl7k3jsyo7J6K1diD5Wnp04PeKqPIKZ3BLUMLrN+DOdi0EW12hmbGjN4zzSM
            vxGhOqCJoOaEuoQ1qL44JJVafCjHGqw1BXG3M3QMYJ5iRrf9r6+HqdVh5hCcGaiI
            nvBbxy1SN9xKkZV5xG7LY+QZJ0Y+CX1K1C+Qq3Pr4ERFVapfupRlh+n3+Wx+DO7F
            OPlNDPSqgRmWCovBRm8+5b7JY3uDCeQWiDgFgKbIkZGTQQ1YmzGoliupNzGuz5lH
            8pKUc/xmj7BgLoby2a8gapoHn+dMo1PEAW1Lt3S1wfzi4qkraaJeK/B0L9IGI4fS
            wLG13ItQCeZxbBN2IAxFou+YwmzMNCdQJPX0icyA7ale9czXiBPkrHpV0ianxarS
            XAHjnjFxq6rjx4C6daiMsHfeMgFArzXjf/O/NPAHtpkhLh3Zg9Cqt432Cioyi6xR
            cf17VkEmzPhq5G+J+7Sug3Mt10WNJQ2HDDSOFcKpT0BTJ8payKrwHbkMPf2+
            =zHmy
            -----END PGP MESSAGE-----
          fp: 283957D2B1919C921CB4AA1CD5725EEFAB586861
    unencrypted_suffix: _unencrypted
    version: 3.13.1
