---
- name: Get user dotfiles
  ansible.builtin.find:
    paths: "{{ role_path }}/files/home"
    file_type: file
    hidden: true
    recurse: true
  register: home_dotfiles
  tags:
    - dot
    - dot_home

- name: Ensure parent directory exists for home dotfiles
  become: true
  ansible.builtin.file:
    path: "{{ user_home }}/{{ item.path | regex_replace('^' + (role_path ~ '/files/home/') , '')  | dirname }}"
    state: directory
    owner: "{{ home_user }}"
    group: "{{ home_user }}"
    mode: '0755'
  loop: "{{ home_dotfiles.files }}"
  tags:
    - dot
    - dot_home

- name: Ensure home dotfiles are symlinked
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ user_home }}/{{ item.path | regex_replace('^' + (role_path ~ '/files/home/') , '') }}"
    state: link
    force: true
  loop: "{{ home_dotfiles.files }}"
  tags:
    - dot
    - dot_home
