---
- name: Get root dotfiles
  ansible.builtin.find:
    paths: "{{ role_path }}/files/root"
    file_type: file
    recurse: true
  register: root_dotfiles

- name: Ensure all root files are owned by root:root
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
  loop: "{{ root_dotfiles.files }}"

- name: Ensure parent directory exists for root dotfiles
  ansible.builtin.file:
    path: "/{{ item.path | regex_replace('^' + (role_path ~ '/files/root/') , '') | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ root_dotfiles.files }}"

- name: Ensure root dotfiles are symlinked
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/{{ item.path | regex_replace('^' + (role_path ~ '/files/root/') , '') }}"
    state: link
    force: true
  loop: "{{ root_dotfiles.files }}"
