user_email: ENC[AES256_GCM,data:NBn5nQNXbp1rqmmidhcJacXgytgfxyT8,iv:EVzQMqSOpGXhkG1wSYRmjI2F6pOdmoMxLby3OUAOPs8=,tag:8yvPpgNmaIJGZVvxe0a4AQ==,type:str]
server_gateway: ENC[AES256_GCM,data:9sMn/phQa18VPSrc,iv:qySZcnxkERb3tQWPmMZPm4fq3VqM7Wq+ov4NT57bmv0=,tag:I+yBW27nFCGYddGN/whAjA==,type:str]
server_hosts:
    sm-server:
        ip: ENC[AES256_GCM,data:dLMU/iQvoKBHmbQsqQ==,iv:xP0xoixmF9P/RlUEWQZXnEivdQaZ3dzFwFrAPMnyhf0=,tag:IQdD+K1KPouyqOkjjBjzEQ==,type:str]
        port: ENC[AES256_GCM,data:xun6Jlc=,iv:J2h+CqI9b+oViWae8+3CfTI26LidF4+6ZOk0qeUsVc0=,tag:hsMFhGCtMsBda1olkX72mw==,type:int]
    sm-rpi:
        ip: ENC[AES256_GCM,data:/3ubwkSYdMWOj4UGNA==,iv:OHrEwalK8GisFAPSsejiR+jL6qqpSET1OqAT+GeRA1Y=,tag:nGXztV7LfiCqiWcjSdv3nQ==,type:str]
        port: ENC[AES256_GCM,data:RnTQoSs=,iv:BpKM6NaRDJ6YZvlYdE9cddc5yULUcDsjQY6xykZGkug=,tag:/pakvmqSqKt4lNWC5CfDxQ==,type:int]
sops:
    lastmodified: "2026-06-21T18:20:55Z"
    mac: ENC[AES256_GCM,data:kAJw1wJFW9rf0ifP0kx65e9Eswi2vTgvHTXS1qvvrlv6uUy7zVUssVy1L83X0WsvDmrImE3J+34z5lXoBlLeRRvE+Xw5vWg8At4wQ5Z66DQhNuRW/X4WujtepM5nwIEewONPKIq8jdI2GGRYg8EzVEMdpsnhqvBi1HpoqIprGfI=,iv:kXxIesBpMKodzuyy4+tv2yWc7NYV7nVS8kcaOV1honY=,tag:i7aC1gNOBKbAB3wHNR9RZw==,type:str]
    pgp:
        - created_at: "2026-06-21T18:20:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAhphIj/6NgMS6HQ6Smhdqm6o8rpGBpz25ncVFlPbHKEvM
            bafdYSYDglozNV9BggDMM3HKg65YsSxySu6MnCLSlbm6J7KdUeNYRsvHN9zRLhGb
            Ka1BwHDY3waptnEya5VimRU7T/CvWmtStEwjCHk9y1DpoglgA5NYfY4jJC3n3vI5
            f8sLo+zenWl8McWnKq4ZvHRJb7SRRYzxXrbdz/s8zxF59pJJfu7jROUT0fpKdQir
            US7oI/SF+lW3Dqyhm39X+EzmVTxd0dKimq5h0StLhG0n0POq4NFhnNymEnZ1ryla
            AMuqYX5HKrfG8FkaZqs55GTYJSXYnqfMmUGaNANZ4Nh3UqOnBeeeIBGt2rxKTKYo
            kOOJdLMQqnJSrNXaroPX3ktY2zySYvXh+dDRVSsOEM05x2O6xD4tX4pYSdV6WNvL
            N7RHnTYP9CmzaMQFXefTg+2BCVbYcu4+poyG6Bn6ZcZrzrsktT1I+7L1eklNLOx1
            af9+FWSnZ5/IWkLLDDBXllXfbY8slpqgCt9CmDBDZpRBq4hp6zGoKgvUa52sHdjw
            TdLt6oChBCsIMdKpvXbM55Awu1aS9/x7fQVOmdYKrPXW4PEzU41Ik8ilTS4iRhNW
            77kxZLvj2jX0ycdueC80R1ffUukKawAKfKPTZoZQjgRVGchtOSs5SvNnJy2e2ZrS
            XgGH/wFN6QLaiwlLEmJTPsk6ILPvhKIumPSE4xUK0sJ+94rtdXFHZRI0WFqP3XRq
            86vt+GYWbBL0bmuEfKlxVn8Q5eEKvv8mU7LXg9YLqMFUbMJ5kQTCAeFLEMVpGtA=
            =ch0s
            -----END PGP MESSAGE-----
          fp: 283957D2B1919C921CB4AA1CD5725EEFAB586861
    unencrypted_suffix: _unencrypted
    version: 3.13.1
