### ── Input ───────────────────────────────────────────────────────────────────
input type:pointer {
  accel_profile    adaptive
  natural_scroll   disabled
  middle_emulation enabled
  pointer_accel    0.5
  scroll_factor    0.5
  scroll_button    BTN_SIDE
  scroll_method    on_button_down
}
input type:touchpad {
  natural_scroll   disabled
  accel_profile    adaptive
  click_method     button_areas
  drag             enabled
  dwt              enabled
  middle_emulation enabled
  pointer_accel    0.5
  scroll_method    two_finger
  scroll_factor    1.5
  tap              enabled
}
input type:touch {
  events disabled
}
