### ── Floating Rules ──────────────────────────────────────────────────────────
for_window [title="grimshot"]      floating enable
for_window [title="copyq"]         floating enable
for_window [app_id="foot-dropdown"] floating enable, \
    border pixel 1, \
    resize set 60 ppt 60 ppt, \
    move position center, \
    move to scratchpad, \
    scratchpad show
