ansible_become_password: ENC[AES256_GCM,data:iJ/axZNga4Ybe1U=,iv:V77YpfTi26+t2m23pOo/WVO9IEx5suoz6CGwRPDuNIY=,tag:dDMBf3hkr7hxnlOJN9tPPw==,type:str]
sops:
    lastmodified: "2026-06-19T18:38:31Z"
    mac: ENC[AES256_GCM,data:ZRTJqCaJD+A26hP8ybx3Z3BXGSWe2gW/8TZ0+YUYKXw7yZzXAnuJKTMzmE65MwiqWEVHwcNturxib1C8hUJzyAGEGOolCmArMoQtTOzBOkLHhn0DF/QqMNpsuZJAd3GL3Fry7VtzELlslV84si3Z8iOhm04rzbsGnQRMBzY36ow=,iv:hsiHIjH/AGZkPAo6qRPO/Vfpdo/7e6BVXQLJJqyME3Y=,tag:5D28lI6eKXpvd42O8KT/4Q==,type:str]
    pgp:
        - created_at: "2026-06-19T18:38:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//cJXe2zoSbwFC5A1Xsdl5P7DdSxAEJUbQXC1KTJcOXyHu
            5DDk12OOuGWSw/L2E7ED4Tp7b0lda+1LgoeOH9Nam9ab7CvAhs3S8RFKUE5MA+Bj
            3gagdAGsmAK2PTrnEdidqFBZ01QPVLM4cc7yHR4OKcUMrJEEIxQj54J9jpdBpyyK
            DmEOw8gZ23ak/j6OfIHqNOjY9NQ61Fu0tNexChr+ElFYRGltUIY1u3z+8NmrMH1E
            qDwbFFQ7m3/JuVIpOXBRRfG9/x4BVteCMIe8cmoRMH7Jk/N9bh9Q+3RDHnpv/apw
            0NM0ADtIo3Kp+ALs2qBOO5wjekr7P6bDtU7HZD4yGY+wMyyg2VF0M/sDETQVhINM
            kdQbEIpyLEWTlJdeuJmUK3hnsoa1g3B38YV0WIf9xauIhCT5QHT6QxDsUo9ig1+N
            TUK0SP+/OdPqp8h3OAHzsO9DoEFH2vyF0nKPBjR+hYTA3jD66ydOYaKOhRsN1QiH
            d8oqCrxPP7iEKFSBgHFXz33+fkHk1M/AYbntoUkfKtDQDvWhnihJzLvqt+zDNlKY
            9mOZB/k9RfQ+sDn9YxYwPpwAQa6jLzVpCZKTWK98Pj8wGObXQd66OS9XEnq2HcVk
            siQx38eRYuP74M5VMOgzXlyLjIPV6y7pVvKW255NCpWVIWPAvdokpiIuoqP5yfrS
            XgFAN2WPhNS1qGuZ7YqxXNKHkf8yI8Mg6+UInKYDVkh6M1JcjMuh6e5GdOeu7LbJ
            1Oo+6LlatZMLBtEE3n19C8LigB14QnmGwkejzZRV/oHEj76oU014Rr/nBft4y0s=
            =XKjM
            -----END PGP MESSAGE-----
          fp: 283957D2B1919C921CB4AA1CD5725EEFAB586861
    unencrypted_suffix: _unencrypted
    version: 3.13.1
