---
- name: Ensure local kube config directory exists
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/kube"
    state: directory
    mode: '0700'
  tags:
    - virt
    - virt_k8s

- name: Fetch kubeconfig from server
  ansible.builtin.copy:
    src: ~/.config/kube/config
    dest: /tmp/k3s-kubeconfig.yaml
    remote_src: true
  delegate_to: sm-server
  tags:
    - virt
    - virt_kubeconfig

- name: Rewrite kubeconfig server address
  ansible.builtin.replace:
    path:    /tmp/k3s-kubeconfig.yaml
    regexp:  'https://127\.0\.0\.1:6443'
    replace: "https://{{ server_hosts['sm-server'].ip }}:6443"
  delegate_to: localhost
  tags:
    - virt
    - virt_k8s

- name: Deploy kubeconfig
  ansible.builtin.copy:
    src:  /tmp/k3s-kubeconfig.yaml
    dest: "{{ xdg_config_home }}/kube/config"
    mode: '0600'
  tags:
    - virt
    - virt_k8s
