---
- name: Download python3-kubernetes
  become: true
  ansible.builtin.apt:
    name:
      - python3-kubernetes
    state: present
    install_recommends: false
  tags:
    - virt
    - virt_k8s


- name: Download kubectl
  become: true
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/{{ {'x86_64': 'amd64', 'aarch64': 'arm64'}[ansible_architecture] }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  tags:
    - virt
    - virt_k8s

- name: Ensure kube config directory exists
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/kube"
    state: directory
    mode: '0700'
  tags:
    - virt
    - virt_k8s
