---
- name: restart sshd
  become: true
  ansible.builtin.systemd:
    name:  sshd
    state: restarted

- name: reload nftables
  become: true
  ansible.builtin.systemd:
    name:  nftables
    state: reloaded

- name: restart fail2ban
  become: true
  ansible.builtin.systemd:
    name:  fail2ban
    state: restarted
