# -*- conf -*-

font=SauceCodeProNerdFont:size=14

[scrollback]
lines=20000

[url]
launch=xdg-open ${url}

[cursor]
style=block
blink=yes
color = ffffff ffffff

[colors]
alpha=0.85
foreground=ffffff
background=000000
selection-foreground=000000
selection-background=00ff00
regular0=1a1a1a
regular1=ff0000
regular2=00ff00
regular3=fda50f
regular4=0000ff
regular5=888888
regular6=00ffff
regular7=ffffff
bright0=666666
bright1=ff5555
bright2=00ff00
bright3=ffcc66
bright4=5555ff
bright5=cccccc
bright6=66ffff
bright7=ffffff

[key-bindings]
scrollback-up-half-page=Page_Up
scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
scrollback-down-half-page=Page_Down
scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down

[search-bindings]
cancel=Control+g Control+c Escape
commit=Return KP_Enter
find-prev=Control+r
find-next=Control+s
