apiVersion: ENC[AES256_GCM,data:V/o=,iv:1Wu2ouZS/OrdddxPH6DqboAsDQ23KhW+x3gb2XVKaPg=,tag:oXxh6Ek4gVlYcudEQHZPUQ==,type:str]
kind: ENC[AES256_GCM,data:JG9DiS/4,iv:lEpDWeNGWNtLeMeA0I1+XBZFYi9o7V0kzF+iYyy6QBk=,tag:+VoTnOSS+pGVSlsOqs4WZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o/B1Y3VYYhPcvnsKAxZDj/M=,iv:J3AOX2ScLYq7Pv9KtnO+xrwobK0ckRuUYxF603Q7O3c=,tag:ZP0lBF2n5wzxGWFTs6UvhA==,type:str]
    namespace: ENC[AES256_GCM,data:DUiDHiBT1MiC,iv:/ZGZFHdpot8upFyfuL3LZ3KXrD6XUePLzCvjYvDLuko=,tag:pE/E0sgeRkz5/v9IR3+J8A==,type:str]
type: ENC[AES256_GCM,data:cWamHgxq,iv:JKIvN3np2q0f1/ItVAHUr0UMHY1i7I9MY9O0G/xjQLA=,tag:qts1K78+l69W2Yt3KuWRVQ==,type:str]
stringData:
    INVENTREE_DB_USER: ENC[AES256_GCM,data:bYyAEiI+GyR1,iv:0QaiUAI0+t0aUlp74y37RtBrijdCECHSeiQl5QO50TQ=,tag:YZ9iC0Dz/s1b6QJE3kBEKA==,type:str]
    INVENTREE_DB_PASSWORD: ENC[AES256_GCM,data:P1AmpYmEZVjo,iv:bVHiZeVLvG3xSJC9WDKnWCIPeS8kjF5g2N5nRTmDKb8=,tag:IbsVoczADFS8ER2gGMHX0w==,type:str]
    INVENTREE_DB_NAME: ENC[AES256_GCM,data:IRkfeQOu1hNt,iv:yCUHcGxo1JfJcIteIKilgWpL5ZxWnDk+wCSEtP5/hh0=,tag:VR/zBqdeRiISaMr9+83JKA==,type:str]
    INVENTREE_ADMIN_USER: ENC[AES256_GCM,data:5BI/5Oo=,iv:EBfUgJkhRD8rdwq30WY4Jb6XVw8Cp1wdbPnMn2/ioGU=,tag:eDu0T2iEl1KPZFxpKCAk7g==,type:str]
    INVENTREE_ADMIN_PASSWORD: ENC[AES256_GCM,data:0oisnjE=,iv:ldCnoixZ2OacNp587Ym089vX7y8OuJ5qC4MFoRnLI0Y=,tag:El3dKWhEm/qsTkI0QCcHEA==,type:str]
    INVENTREE_ADMIN_EMAIL: ENC[AES256_GCM,data:bKxx6QDgMCtlamyTOWvw/A==,iv:DeWFtZKegiTFSsdGiggrF/KfdfFT3lMpP/nImSEK2VQ=,tag:ggA/xi2e/MmIzLIrT/dmcA==,type:str]
    INVENTREE_SITE_URL: ENC[AES256_GCM,data:HS3y6K5sQAx58tJ3ISFkY3OzLhR4WSfE7Jw=,iv:WiX1gk+5ccA02TYzjsJByJ6Kb3n2Kyc2rSB9hE39pvg=,tag:63dwL1x1j2GCGp2yK/vTDg==,type:str]
sops:
    lastmodified: "2026-06-21T09:07:12Z"
    mac: ENC[AES256_GCM,data:YIqlQlLHW8dirapy+YdmftiE0RcycAiC6Un99UkbzdU4giWZQEVTir4aReEGyaf9yVYrFm8zJbSGdzg3nY46mYcSbgNmyFUooG0cRgyV0OFH/pDvc2qAb3cQwXs2xA0aNd0WWynOITOnmVwQon9nDhKx8mI2JEs5nt9KD879CnY=,iv:sJE4yVfDe0+VAZ9q2m8sbW4LY4Z55NVEGhyHsXnptQ8=,tag:DKjYslfWCc7VrQ7hxuunFw==,type:str]
    pgp:
        - created_at: "2026-06-21T09:07:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//eSlJXUhXz9WNYSQUcUDFGDtPF63pggp7IQNzWRCq+rh3
            kOAjtRfZ7EB8w7V6aQh6054uTSaWLtFm4h+W0X8xG/FWJf9t06InxmKnxeUg14BA
            1KeKoTy0Mqd8aB17Avo4Pq6a7o3SYQF1W+SIwGU/pWOSg6tDmOhsDhyjE93CCpPa
            2rsLQAwnk9SU7YRym3V6O717MsEwnguPWTW0QqF7s6iuKj5setpy4lphx6i9knpy
            MuyLQWJIC5SCOEgA+YtKCt7UJ1IATIyJD3cQtX524d/CxPf7sfXeZESX5TbYmmSs
            X9392ixiYelC7g2yF77ZYAzTh1Rh6ItUAOtyHA/yW5dncUyGwgM/SSaqJfMuMK1B
            L/7c9akvRUiEV9piWn1UqFs2F12567xjxGZ+wS0k7kAZ/HDLrI69vDPwMIZ4EKp/
            zP4fTxchPUi/BClE5vVVR6KrDMZFM5GDWDXBX3QhGyzZ+1dWTo4UWHRl9HpSisfz
            E8UkyuMNpUWVkgSEKYNQ57Jc3GivsEFnHC2aPMeXb329KmiEFQfXa3xXc2EtLTVZ
            a0wjK7vNHQ1BugcRyjnrgEWE3pO2FGAd0FGbgNU3J+XHOCprAtK6AOzgP8q8WfYL
            M8TZfR25t3yON8Upk70uCVtUmt7BnylF33NfGmvAKlYyBNPTOlyYOXoSe5FfOrTS
            XgEKPFJ8py0aTrNikN8OXIVeWSAae/g4n7tZk6CQiES6o1kuI/O/jLXIVji228GR
            GNcLiXUqkq1iBTbOFyHCsKABc5rZDS1uca2rud/JNK6ISjOP7MVfZ+U9VcUNSlU=
            =Crez
            -----END PGP MESSAGE-----
          fp: 283957D2B1919C921CB4AA1CD5725EEFAB586861
    unencrypted_suffix: _unencrypted
    version: 3.13.1
