ansible_become_password: ENC[AES256_GCM,data:jCq1tWzihy93174=,iv:QlvbyFMBB0LTXqRkapp2Yfb9qedGFk+hnFFjZ+ONaM8=,tag:bJfd2L/zyEic69fYrtQjEA==,type:str]
sops:
    lastmodified: "2026-06-20T11:46:30Z"
    mac: ENC[AES256_GCM,data:tzRPAUE2Ja7YB5REmFsO6UnRTk//QqkQqr9tPpFkA1iiEYZVJ8OJaGN5+9MPuy0CHRTB6zsFBdpy3vtqrERqKB37QPxDlLG2A2om80hbcWQU+1WhK1YBLzJ/9IARj0f21O8c6hZ8ZeNoaMUHwjWULS+hAafUeUQiMNSJ5Qjxjes=,iv:xeH8DRMtw5Mhxn+sKK8AAzpBG0RnWpQXwRAUrfBAlsE=,tag:rYaVAjnVPlfde1JhgaB0Cg==,type:str]
    pgp:
        - created_at: "2026-06-20T11:46:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAiwiEeOGp2jWs7vYzYBKu7C+DIk05aIkpopcYagUNAIs4
            itqx92vly+bZ/dBq0Xe3qaXqeJEXF8VfLnkcJqr3N6r730svzWHQ6VivP76bztC1
            idvyy6cUGXaOuSSpASPZjncAyAL581Hu+z/S4dTqeZPX+5Ii/bVkg72hCDpbX1Pu
            JNMnUM7N0xpLGVbxgzXoWHhH8OjwGPHEs/XcKFswxRZcvqY+FhXMznTuP1p0O5KQ
            /uyg3SrpkY7/SQDC87G0zxBnlcw1jqMGOE5bL2NsC4gCn3vyH5FcbHhCBCEa0Iah
            onCs/BJVonJ7AX9TmiENSu93Ja3r61OAY4HISHc1Bk2VoZfl0MhivffHC6diQJPk
            5U+lseOplaaUADg3lkkLC2SOZFKXUb9+KPxu0zIX9Yt4nxhEiwzsPYznObZlPjV0
            xGH9ps71+M67CPOdqtZ4Ndsn6b/v+qmMpoa9GwRW/EGJ37PRjyJVohq1XItUYtkA
            1rK4Y9fSo6ap4MAxYCCLVmijQmO741SHHR1z0S4sYr+z3BGqOJcRpcBmluciR4Np
            wJhNLuY8Avy0Cns6Kl4pQqEwJnxkHGo93N3bpEwg+0Kt/9bMqTxtW4YGBoB8GEGf
            MHNu/HZhMtVPnV89msPkIJkXydCvKfvjkigcSTbRFoKKWRI06cRBP9fZBXMx0yDS
            XgH686plUZAV44WPWT/CMB87dXucziAAIdCH85wAA9kDCKNtAoVEDvkeT5VaBjHC
            MImcWJ6pNYVTdaNknNWKGyF8pPRHWKe6wGdlI+PmnZp11rUDvfN3qhut8/+mGac=
            =XV2G
            -----END PGP MESSAGE-----
          fp: 283957D2B1919C921CB4AA1CD5725EEFAB586861
    unencrypted_suffix: _unencrypted
    version: 3.13.1
